### ISSUE TITLE
where

### ISSUE THREAD

**Issue by rafalohaki** [h4xrOx/GameSense.is.crack.CR4cKCRACK#14]
where is website and discord? :(

**Comment by Triquetra1337** [comment]
its just rat lol. u can delete

**Comment by rafalohaki** [comment]
lol

**Comment by falseCloud** [comment]
rat :)

**Comment by h4xrOx** [comment]
It's not a rat.  Esoterik esotk es31n estkk , Kitty sad kitten so many more names,  deleted the server, I made him admin, gave him my webhooks my ip and he didn't even wonder why,  when posted a part of an MC dump with his supremacy client; he posted a fake FBI background on his page. Deleted the discord, and neverlose, and moved his server because I dumped a huge secret; skeet is so private because the invites are for "fem boys" he give the pedo nudes for invites. Skeet is secret for it's a pedo playground to solicite children.  The skid can't even properly paste. Around 2018 skeet because a wrapper and api, no longer a reseller or content creator for skeet , a Russian cheat because because he didn't drive in revenue and the Russian engineer from Kiev that works for Microsoft, got out. Gamesense is OTC. And my webserver is on interserver pointing at neverlose.is and logging , using all resources to make sure the police got everything this this child awaster.  My domain in namesilo, parked . I'll be releasing all the fake cracks , plus the real source of 2018 skeet I dumped from his hosts here shortly. Don't buy that neverlose.is and stay way from this guy he's sick. 
I guess he thought my account was really gamesense-pub@outlook.com and I guess he thinks you all dumb because his posted a folder from 2015, saying he cracked neverlose.... 
![Screenshot_20210830-225549](https://user-images.githubusercontent.com/65768277/131520096-f6be7efc-27e5-4a05-ab9d-0b29a8befc6e.png)
![Screenshot_20210830-222102](https://user-images.githubusercontent.com/65768277/131520109-f56bd74d-2691-41e0-8843-988e3aa54ba1.png)
![Screenshot_20210831-035655](https://user-images.githubusercontent.com/65768277/131520111-89551949-b503-4b4f-a979-b0bfd76c6013.png)
![Screenshot_20210830-201007](https://user-images.githubusercontent.com/65768277/131520117-5ebc1cbf-bb5f-4cf6-a55a-8680955c1462.png)


http://master.download.ispsystem.com/htdocs/htdocs/6/vm/

**Comment by rafalohaki** [comment]
great to hear. great work
