### ISSUE TITLE
r

### ISSUE THREAD

**Issue by mgrs234** [h4xrOx/GameSense.is.crack.CR4cKCRACK#3]
what the fuck

**Comment by h4xrOx** [comment]
as esoterik said " gamesensepub/GameSense.is: Since they crack it and sell it for $35 (Obviously above the price I originally had it for) I decided to crack it for them. "  ( but you cant see that; I can though )
![image](https://user-images.githubusercontent.com/65768277/126603110-e45db65e-ce3d-4753-b561-76ef848f0df2.png)
