### ISSUE TITLE
Psychosis...?

### ISSUE THREAD

**Issue by mtfy** [h4xrOx/GameSense.is.crack.CR4cKCRACK#30]
Issue: your psychosis
Solution: [gamesense.vip](https://gamesense.vip)  when?

**Comment by HurbTheDude** [comment]
never

**Comment by h4xrOx** [comment]
![image0](https://user-images.githubusercontent.com/65768277/160032011-a1ac1de7-fda7-488f-acea-f7e878f3153a.png)

![144723366-c0420fa1-e844-4b56-a8da-b5e84adcc3ba](https://user-images.githubusercontent.com/65768277/160032165-f7c25f59-9e35-4e69-8ddf-b0790f2f9358.png)


I think the ones you want are private but pyskeet I made public. Most of this is true except it's bait. That's why you get the pictures. Bad guys bite

**Comment by HurbTheDude** [comment]
🤣🤣🤣🤣🤣

**Comment by mtfy** [comment]
I mean seriously I gey your point regarding the russians behind the scam. But the README.md of this repo is hurting my eyes 🤧
Also that looks like NL user interface with skeet theme, I like it, but what’s the point?

**Comment by h4xrOx** [comment]
> I mean seriously I get your point regarding the russians behind the scam. But the README.md of this repo is hurting my eyes 🤧 Also that looks like NL user interface with skeet theme, I like it, but what’s the point?

That is neverlose first launch , and first issue. Which is basically aimware, which was basically because of no xframe headers configured on mybb so was caching the cookies of last to login on the header. Click jacking with burpsuite.  The gamesense is gamesense. Similar thing here. The static site never been updated still has vulnerable versions of jQuery from the free template on punbb which isn't even maintained anymore. You can dynamically access the site a few ways, but the easiest is to just goto: https://gamesense.pub/forums/cache/   , you can use the gamesense.dll repo, to check the Dsn and rebuild and launch from sentry, as I posted gamesense forums, just how they got it from the Russians whos IP and names are in test.sql in my gamesense forums repo.  In that repo of their forum I left a few things not GS. Like rpc_sindig is a script made by google. it catches core libraries and auth; randomly; you find it in many projects, across many platforms; https://oauth.googleusercontent.com/gadgets/js/core:rpc:shindig.random:shindig.sha1.js?c=2 , run some flags in chrome to no sandbox,  and inject with custom ha extension, and rebuild o , .  On my discord I give detailed account of it . I shouldn't have to tell yhow the ou it polls vi open API,  you can literal. Just lets assume you you  we can grab

**Comment by mtfy** [comment]
Well explained but I disagree on the `/cache/` thing you mentioned. PunBB is the legacy version of [FluxBB](https://fluxbb.org/) and is heavily outdated as it is not supposed to be used for production, which is why FluxBB exists. [GameSense](https://gamesense.pub/forums/) uses FluxBB 1.5.11 so I heavily doubt there are any major exploitable vulnerabilities, unless they have modified the core files instead of using hooks.By the way, can’t seem to add you on discord for some reason. Please double check whether you’ve blocked Motify#0033

**Comment by h4xrOx** [comment]
> Well explained but I disagree on the `/cache/` thing you mentioned. PunBB is the legacy version of [FluxBB](https://fluxbb.org/) and is heavily outdated as it is not supposed to be used for production, which is why FluxBB exists. [GameSense](https://gamesense.pub/forums/) uses FluxBB 1.5.11 so I heavily doubt there are any major exploitable vulnerabilities, unless they have modified the core files instead of using hooks.By the way, can’t seem to add you on discord for some reason. Please double check whether you’ve blocked Motify#0033

Thats what I said. On my phone its hard to type. but fluxbb is a fork of punbb. I literally say its not maintained. They fixed the sanitize issue with tooltip and popover. That isn't the issue in which I exploit.  Here I exploit:  So just goto the cache directory and http request these, or click them here, download them and store them as local overrides. I dont do this to get attention; I dont sell anything; play csgo or care about gamesense.pub. I am also not malicious,. So look really close at the screenshots; You cant debate this. I do this to catch bad guys. not monetize.

https://gamesense.pub/forums/lang/English/mail_templates/activate_email.tpl
https://gamesense.pub/forums/include/template/redirect.tpl
https://gamesense.pub/forums/include/template/admin.tpl
https://gamesense.pub/forums/cache/.htaccess
                               
**jquery | 3.2.1 | Found in https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js**  

[jquery | 3.2.1 | Found in https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js]

![image](https://user-images.githubusercontent.com/65768277/160070157-dceb8dec-ee37-4932-9b0e-02220f5f7aad.png)

As shown in the picture; download while on the directory with dev tools open on chrome via http request: " admin.tpl " and " redirect.tpl " cache directory is dynamic: 
![image](https://user-images.githubusercontent.com/65768277/160074882-70de387b-e3af-48c5-bb16-3a9ef20597a0.png)
 ( follow my instructions pinned in my discord )  once you do that you will  see  https://%20alias/ show up in sources; then fly over to application; where you will see cached a session cookie for admin.tpl and redirect.tpl and activate_email.tpl. check? or Poll for vk_escape; dont need that at all; we can use some put post and get magic ( as you see is allowed with the htaccess file , and I upload shellcode backdoor in the cache directory.) :  you'll see in the picture below; I have database support with metasploit and session. this isn't a debate.  What is in that cache directory? the cache_config that alllows me to match criteria to   to elevate credentials. Because I bake cookies:

![image](https://user-images.githubusercontent.com/65768277/160081076-846b54fe-010e-4aab-aa6a-e8368a65d0b2.png)


What are the groups? 
define('PUN_COLORIZE_GROUPS_LOADED', 1);

$pun_colorize_groups = array (
  'style' => '.gid1 {color: #00BFFF; font-weight: bold} .gid2 {color: #ff9933; font-weight: bold} .gid5 {color: #e61515; font-weight: bold} .gid6 {color: #e61515; font-weight: bold} ',
  'groups' => 
  array (
    1 => 'Administrators',
    2 => 'Moderators',
    3 => 'Guests',
    4 => 'Members',
    5 => 'Premium user',
    6 => 'Beta user',
  ),
);
**WHAT ABOUT THE NUMBERS WE NEED FOR ADMIN?** 
define('PUN_ADMINS_LOADED', 1);

$pun_admins = array (
  0 => '2',
  1 => '3',
);

**THEN WE CAN REDIRECT AND GET FOOTER?**
![image](https://user-images.githubusercontent.com/65768277/160080638-6715c1c3-a7f3-4e0d-92b1-00f9c52ea7de.png)

![image](https://user-images.githubusercontent.com/65768277/160079187-53c25f2c-1b91-479a-92f1-639fcc8fa868.png)

![image](https://user-images.githubusercontent.com/65768277/160078791-9d710e51-ac6a-4428-a5a3-c13bd45dd73e.png)

![image](https://user-images.githubusercontent.com/65768277/160077856-02d0dbf6-3b87-4fea-8645-0b8c3ef4fbdc.png)

![image](https://user-images.githubusercontent.com/65768277/160076934-1c3a940e-ea65-4afa-ba9c-eca068c3c76c.png)

https://gamesense.pub/forums/lang/English/mail_templates/activate_email.tpl
https://gamesense.pub/forums/include/template/redirect.tpl
https://gamesense.pub/forums/include/template/admin.tpl
https://gamesense.pub/forums/cache/.htaccess


![image](https://user-images.githubusercontent.com/65768277/160071137-0a375c98-b5ec-4164-a282-b728f7da4577.png)

**Comment by h4xrOx** [comment]
"[GameSense](https://gamesense.pub/forums/) uses FluxBB 1.5.11 so I heavily doubt there are any major exploitable vulnerabilities"

the static site uses punbb; files are still stored in the database, Everything is vulnerable; because people are vulnerable; they have misconfigurations everywhere; look they lock the install directory for punbb " forums/install.php " but on the static site this leaves the install directory for flubb open: 

![image](https://user-images.githubusercontent.com/65768277/160090439-a260c9a3-58cd-4c67-ad0c-9104584409bb.png)

Now 3 weeks ago I did what should have been a subdomain takeover; because they still had records pointing to unused service on steam ( the old web api key for admin account on steamworks: [https://steamcommunity.com/dev/apikey/activate?F4EB2D6CED2B4BDDAD9DF913287E6768](https://steamcommunity.com/dev/apikey/activate?F4EB2D6CED2B4BDDAD9DF913287E6768 ) i activated it , ** www.gamesense.pub on steam; and it shut their site down for a week because everytime anyone went to " gamesense.pub " it redirected them to www.gamesense.pub; because they misconfigured the DNS records.  server.gamesense.pub, 5.61.173.14 aka RSM.GG was set as Name Server, www.gamesense.pub was set as A , and authoritive record, while the @root " gamesense.pub" was MX record.

![image](https://user-images.githubusercontent.com/65768277/160092007-a850345d-47f8-408a-af28-1a0ef7f8d0b2.png)
![image](https://user-images.githubusercontent.com/65768277/160092111-af7fa363-c829-4550-a4a6-c576ab1fffb4.png)

```; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.68.rc1.el6_10.8 <<>> +additional +multiline +norec +dnssec www.gamesense.pub. @165.87.13.129
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17862
;; flags: qr ra; QUERY: 1, ANSWER: 0, AUTHORITY: 8, ADDITIONAL: 13

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 4096
;; QUESTION SECTION:
;www.gamesense.pub.	IN A

;; AUTHORITY SECTION:
pub.			104705 IN NS v0n1.nic.pub.
pub.			104705 IN NS v0n0.nic.pub.
pub.			104705 IN NS v0n2.nic.pub.
pub.			104705 IN NS v2n0.nic.pub.
pub.			104705 IN NS v2n1.nic.pub.
pub.			104705 IN NS v0n3.nic.pub.
pub.			36036 IN DS 53776 8 2 (
				3766469C89AF5ECA8E8C5852E359396294057677C5AE
				8CA9C641422D7237BB4F )
pub.			36036 IN RRSIG DS 8 1 86400 20220215050000 (
				20220202040000 9799 .
				CZ2aUUV60soEacvO45z2l5tizza1muS44VDHRrMGJ3UK
				K7fG2v5YQG7Ch08aff2QLM++vRlJKufkL455jnGLnsYj
				0duhJ9BY9TMOpBswRyF/ItCWnGxGuPgnEwiHqO0EPAjw
				tRCvwtWzUzO53yepKPsKhNegnfXPIaMMglpP99nDu877
				+jy/c9uReAeQZCGTj8xg0FH1Ba9S+CCZADtMoU5/L+zm
				9z0gSrB6jNQqX37/LJVesHWcjBFOn5HZIolJh/+Xb4GT
				vZ2IFsdOf32p2ofFH//ofjfj72srkb8TC/aknMnOyZYv
				nzX7XWnH+xODX3DUc3P57/ZB624J25KCig== )

;; ADDITIONAL SECTION:
v0n3.nic.pub.		55448 IN A 161.232.14.7 Location: Toronto, Ontario, CA
v0n2.nic.pub.		104705 IN A 65.22.30.7 Location: Toronto, Ontario, CA
v2n1.nic.pub.		104705 IN A 161.232.15.7 Location: Toronto, Ontario, CA
v2n0.nic.pub.		104705 IN A 65.22.31.7 Location: Toronto, Ontario, CA
v0n1.nic.pub.		104705 IN A 65.22.29.7 Location: Toronto, Ontario, CA
v0n0.nic.pub.		55448 IN A 65.22.28.7 Location: Toronto, Ontario, CA
v0n3.nic.pub.		104705 IN AAAA 2a01:8840:f8::7
v0n2.nic.pub.		104705 IN AAAA 2a01:8840:20::7
v2n1.nic.pub.		104705 IN AAAA 2a01:8840:f9::7
v2n0.nic.pub.		104705 IN AAAA 2a01:8840:21::7
v0n1.nic.pub.		104705 IN AAAA 2a01:8840:1f::7
v0n0.nic.pub.		104705 IN AAAA 2a01:8840:1e::7
```

**Comment by h4xrOx** [comment]
> never
![Screenshot_20220325-045535](https://user-images.githubusercontent.com/65768277/160098750-7a300d2b-5a15-42d0-8204-581155e9c679.png)

I host auttaja locally, and setting verification for it ensures that each and every user is redirected to me with no possibility of using a VPN, proxy or script blocker on first join. Why auttaja? The API, allows me to access discords developer API when I add regex for custom commands with OnMessage. This is because the shit that hurts your eyes is bait. Real information to get the attention of the targets; displayed in a way to invoke them to confront a skid. It works too, because here you are.  Red Hats cannot be bought, won't take instruction, and won't work for money. Economy is slavery.  Life is short. If you grind do that work for your dreams, fulfil yourr will. You can take a black or white hate and give them enough money to do eithers job. They are they same. Slaves exchanging time for that which is already theirs. Who give me anything I can't take? Real hackers do not sell anything. Because there's nothing anyone can give me, God  created  the world and gave his children authority over the Earth and  free will so that we could create .  If I tell a mountain to move,  it moves.  Red hats watch, allow you to do what you were given authority to do; so beit that you not hurt any of these little ones.  God told me if anyone hurts any of these Children it would be better for them to tie a rock around their neck and cast themselves into the sea. Families should think as one, act as one and believe as one. I only work to protect the little ones, for my will is my father's. You guys really are no threat to me or anyone. Games are for kids and while you log and tell some of your users names like it's a dox. Adults and professionals don't use anonymous handles and fake names. Children should to be protected, because predators, criminals and only people that have reasons to hide wear masks. Be proud of who you are, because the day is soon coming that all things thought to be done anonymously will be known by everyone. A Red Hat Coming. 
```/**
 Manage callback and print data logger.info
 @verifyPublic
 @on_message
 @return IP{user}
/**

# IP address using Regex
import urllib, re

data = re.search('"([0-9.]*)"', urllib.urlopen("http://ip.jsontest.com/").read()).group(1),
app.logger.info(on_message),
print data

# Function for Validating IP
def Validate_It(IP):
 
    # Regex expression for validating IPv4
    regex = "(([0-9]|[1-9][0-9]|1[0-9][0-9]|"\
            "2[0-4][0-9]|25[0-5])\\.){3}"\
            "([0-9]|[1-9][0-9]|1[0-9][0-9]|"\
            "2[0-4][0-9]|25[0-5])"
     
    # Regex expression for validating IPv6
    regex1 = "((([0-9a-fA-F]){1,4})\\:){7}"\
             "([0-9a-fA-F]){1,4}"
     
    p = re.compile(regex)
    p1 = re.compile(regex1)
 
    # Checking if it is a valid IPv4 addresses
    if app.logger.info(on_message)(re.search(p, IP)):
        return "Valid IPv4"
 
    # Checking if it is a valid IPv6 addresses
    elif (re.search(p1, IP)):
        return "Valid IPv6"
 
    # Return Invalid
    return "Invalid IP"
 
# Driver Code
# IP addresses to validate
IP = bot.callback("https://auttaja.io/auth/verify?{user}")return IP{user}, 
print data
```

**Comment by mtfy** [comment]
Props for well-detailed documentation on the above post. I'm currently too tired to read all of that. But regarding [@itsnuub's project](https://gamesense.bar)...

> > ![Screenshot_20220325-045535](https://user-images.githubusercontent.com/65768277/160098750-7a300d2b-5a15-42d0-8204-581155e9c679.png)

This is a joke by @itsnuub as both URLs are honeypotted. Why would anyone allow API endpoints being discovered just by statically analysing it? This proves the benefit of honeypotted endpoints.
Translate `maahanmuuttaja` from Finnish to English

**Comment by nvx0** [comment]
Don't even dare to hate on the king of all the cracks.

**Comment by HurbTheDude** [comment]
Your Quote on quote "analysis" of user groups.. is wrong, there is no such thing as "Beta user". That's why they have a completely different site for it. You are also forgetting the lua moderator user group, then again it's hard to know everything about your "gs forum" is afkboost 🤒

**Comment by h4xrOx** [comment]
## I got gamesense.bar from reversing test.dll from:
- https://api.github.com/orgs/gamesensepub/repos
-
## You can goto my repo and copy the links to download the specified files. You can also GET , wget, curl, or brute dir to confirm. Gamesense actually had a beta home.php which was linked by the features page as well.
# example: ```https://gamesense.pub/forums/lang/English/mail_templates/activate_email.tpl```
- download from gamesense.pub in browser
-
![Screenshot_20220403-003212](https://user-images.githubusercontent.com/65768277/161413548-2308720a-c47c-46e0-8551-fcc84fea210d.png)
![Screenshot_20220403-003027](https://user-images.githubusercontent.com/65768277/161413549-6d14c898-091f-4df2-b98c-78ec343af401.png)
![Screenshot_20220403-002837](https://user-images.githubusercontent.com/65768277/161413551-709b1c82-dafb-4705-b6c9-05269141c13e.png)

**Comment by h4xrOx** [comment]
![Screenshot_20220403-005126](https://user-images.githubusercontent.com/65768277/161413864-14369c74-eceb-4c20-9b14-4093a2480db2.png)

**Comment by nvx0** [comment]
Psychosis again...

**Comment by h4xrOx** [comment]
> Psychosis again...

# # # # https://github.com/h4xrOx/gamesense.bar/blob/main/testingdlldata.cpp
####

![Screenshot_20220403-090901](https://user-images.githubusercontent.com/65768277/161432048-971762ff-af48-4a01-baa6-31a3896832e7.png)


![Screenshot_20220403-090554](https://user-images.githubusercontent.com/65768277/161431898-97c9139b-beb2-4737-bc9a-a404b9938cb4.png)

**Comment by h4xrOx** [comment]
https://gamesense.pub/index2.html

![Screenshot_20220403-104941](https://user-images.githubusercontent.com/65768277/161436373-e7a7677c-f15f-4077-9857-52b66f9e2788.png)


https://gamesense.pub/features.html
![Screenshot_20220403-105240](https://user-images.githubusercontent.com/65768277/161436519-7c51c7a6-081d-4179-b73d-2bde557636bd.png)

**Comment by souffiw** [comment]
Harox do u have index2 still?

**Comment by mtfy** [comment]
> Harox do u have index2 still?

https://web.archive.org/web/20220805104544/gamesense.pub/index2.html

**Comment by h4xrOx** [comment]
![image](https://github.com/h4xrOx/GameSense.is.crack.CR4cKCRACK/assets/65768277/9c25e80c-a8b7-46de-8376-e549f2122524)


> > Harox do u have index2 still?
> 
> https://web.archive.org/web/20220805104544/gamesense.pub/index2.html

![image](https://github.com/h4xrOx/GameSense.is.crack.CR4cKCRACK/assets/65768277/68da6f49-4789-4112-be58-f2be428e8c20)

[index2.zip](https://github.com/h4xrOx/GameSense.is.crack.CR4cKCRACK/files/12249075/index2.zip)


> Harox do u have index2 still?

[signup.zip](https://github.com/h4xrOx/GameSense.is.crack.CR4cKCRACK/files/12249098/signup.zip)
[features.zip](https://github.com/h4xrOx/GameSense.is.crack.CR4cKCRACK/files/12249101/features.zip)
